name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch repo code into ubuntu machine
      uses: actions/checkout@v4
    - name: Compile Rust project
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
